### Exploring session
GET http://{{bettercap_user}}:{{bettercap_pass}}@{{bettercap_url}}/api/session?from=
Accept: application/json, text/plain, */*

### Get events
GET http://{{bettercap_user}}:{{bettercap_pass}}@{{bettercap_url}}/api/events?n=50
# Authorization: Basic ZG9kbzpwYXNz

