# Source: https://github.com/confluentinc/cp-helm-charts/blob/master/values.yaml

cp-kafka-connect:
  image: pinkstack/kafka-connect
  imageTag: 0.0.1

cp-kafka:
  persistence:
    enabled: true
    # storageClass: ""
    size: 7Gi
    disksPerBroker: 1