---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tick-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt

    # kubernetes.io/ingress.class: "gce"
    # kubernetes.io/ingress.global-static-ip-name: oraclepeak-ip
    # ingress.kubernetes.io/rewrite-target: /

    # kubernetes.io/ingress.allow-http: "true"
    # networking.gke.io/managed-certificates: sandbox-certificate
  labels:
    app: tick
    version: "0.0.9"
  namespace: tick
spec:

  tls:
    - hosts:
        - tick-ingress.grafana.oracle-peak.pinkstack.com
      secretName: tls-secret
  rules:
    - host: grafana.oracle-peak.pinkstack.com
      http:
        paths:
          - path: /
            backend:
              serviceName: cookie-grafana
              servicePort: 3000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: tick
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi