# Source: https://github.com/bitnami/charts/blob/master/bitnami/grafana/values.yaml

# helm install cookie bitnami/grafana -n monitoring

#service:
#type: NodePort
#nodePort: 80

updateStrategy:
  type: Recreate
# rollingUpdate:
#   maxSurge: 25%
#   maxUnavailable: 25%

persistence:
  enabled: true
  existingClaim: grafana-pvc
  accessMode: ReadWriteOnce
  # size: 10Gi


service:
  # type: LoadBalancer
  # type: ClusterIP
  type: NodePort
  port: 3000
  nodePort: 30010

metrics:
  enabled: true

  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "3000"
      prometheus.io/path: "/metrics"

livenessProbe:
  enabled: true
  httpGet:
    path: /login
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  httpGet:
    path: /login
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1