---
- hosts: k8
  become: true

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Install a list of packages
      apt:
        pkg:
          - snapd
          - vim
          - curl

    # Install a snap with classic confinement
    - name: Install "microk8s" with option --classic
      community.general.snap:
        name: microk8s
        classic: yes