---
- hosts: all
  become: agents
  gather_facts: True
  gather_subset: interfaces

  tasks:
    - name: "Pull latest oracle-peak-agent"
      shell: |
        docker pull {{ docker_image }}
    - name: "Stop and remove oracle-peak-agent containers"
      shell: |
        (docker stop agent || true) && (docker rm agent || true)

    - name: "Run container in detached mode"
      shell: |
        docker run --name=agent \
          --network=host \
          -e CLIENT_ID="{{ client_id }}" \
          -e LOCATION="{{ location }}" \
          -e MQTT_ROOT_TOPIC="{{ mqtt_root_topic }}" \
          -e BETTERCAP_URL="{{ bettercap_url }}" \
          -d \
          --restart=always \
          {{ docker_image }}
