name: CI

on: [ push ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Github Container Registry
        run: |
          docker login --username ${{ github.actor }} --password $(echo "${{ secrets.CR_PAT }}") ghcr.io

      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.11

      - name: Compile, build and publish Docker Image
        run: |
          sbt compile docker:publishLocal