name: CI

on:
  push:
    tags:
      - v0.*
      - v1.*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest # macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        run: |
          docker login --username ${{ github.actor }} --password $(echo "${{ secrets.CR_PAT }}") ghcr.io

      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.11

      - name: Compile, build and publish Docker Image
        run: |
          sbt "clean; compile; agent/docker:publishLocal" && \
            docker push ghcr.io/pinkstack/oracle-peak-agent-arm32v7